### PR TITLE
Docker-build

### PR DESCRIPTION
**Pull request by valador**
Some fixes for work on docker.

### CODE REVIEW

**Comment by iperov** [comment]
@CeeBeeEh check it please

**Comment by TailaPola** [comment]
If you don't min, leave me contact for private message

**Comment by iperov** [comment]
@CeeBeeEh ?

**Comment by CeeBeeEh** [comment]
@iperov looks good at first glance, I haven't had a chance to test it yet. (sorry about the first message, I didn't get any notifications for it)

@valador just wondering, on lines 4,5 of the Dockerfile, wouldn't it make more sense to set the container's UID to be the same as the UID of the user launching the container? That way you would avoid any permission issues. For example, if my host UID is 1001 and I link to a data folder in my home directory, then the container's UID of 1000 would not be able to read the data.

**Comment by valador** [comment]
> 

Yes, that's right, my user UID is 1000 when building a container, you can pass any UID, but you need to add detect user uid for build to start.sh and pass argument. I'll do it one of these days.

**Comment by CeeBeeEh** [comment]
@valador A simple `id -u` for the user ID and `id -g` for the group ID is all you need.

**Comment by iperov** [comment]
please do something or close

**Comment by iperov** [comment]
1 week and I will close this pr.

**Pull request closed without merging**
