### PR TITLE
Added Japanese language/ 日本語化

### PR DESCRIPTION
**Pull request by osushiski**
from Japan, thank you.

### CODE REVIEW

**Comment by iperov** [comment]
change JA to 'ja-JP'

**Comment by osushiski** [comment]
> change JA to 'ja-JP'

It's done.

**Comment by iperov** [comment]
and follow same logic here https://github.com/iperov/DeepFaceLive/blob/master/apps/DeepFaceLive/DeepFaceLiveApp.py

**Comment by osushiski** [comment]
> and follow same logic here https://github.com/iperov/DeepFaceLive/blob/master/apps/DeepFaceLive/DeepFaceLiveApp.py

Finished, Thank you.

**Pull request merged**
