### PR TITLE
Linux compatibility changes

### PR DESCRIPTION
**Pull request by CeeBeeEh**
A few changes to help with Linux Docker compatibility. Added an driver option to use "plain" OpenCV to read frame from the camera.

### CODE REVIEW

**Comment by iperov** [comment]
hello?

**Comment by CeeBeeEh** [comment]
Yes?

**Comment by iperov** [comment]
did you read review above

**Comment by iperov** [comment]
nevermind, I will fix it

**Comment by CeeBeeEh** [comment]
I apologize, but I didn't see any notifications on anything about this.

**Pull request merged**
